# Generated by Django 5.0.6 on 2024-06-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0006_cart_cartitem_cart_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
    ]
